### ISSUE TITLE
Resource packs get unloaded by mod

### ISSUE THREAD

**Issue by ArduinoFan0** [V-Fast/BackroomsMod#19] opened 2023-09-19 23:02 UTC
# Bug
Resource packs get unloaded by mod

## Screenshots
![Minecraft_ 1 20 1 2023-09-19 4_55_08 PM](https://github.com/V-Fast/BackroomsMod/assets/100047815/bb03758e-a85e-4dca-809c-5671c2206af1)

# How to reproduce
1. activate resource packs
2. Click on 'done'
3. watch your packs get unloaded

# Expected behavior
no problems

# Informations
- OS: Windows 11
- Mod Version: Beta A0.1.5
- Fabric API Version: 0.85.0
- Geckolib version: 4.2.3
- Minecraft Version 1.20.1
- Logs "No logs available at the moment"

**Comment by Clomclem** [comment] 2023-11-21 19:10
Can't reproduce, closing this.

**Closed by Clomclem** 2023-11-21 19:10 UTC
Labels: bug
